// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: Calculatrice.proto

package calculatrice

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ResultCalculatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ResultCalculatorResponse) Reset() {
	*x = ResultCalculatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Calculatrice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultCalculatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultCalculatorResponse) ProtoMessage() {}

func (x *ResultCalculatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Calculatrice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultCalculatorResponse.ProtoReflect.Descriptor instead.
func (*ResultCalculatorResponse) Descriptor() ([]byte, []int) {
	return file_Calculatrice_proto_rawDescGZIP(), []int{0}
}

func (x *ResultCalculatorResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type ValuesCalculatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TermX int32 `protobuf:"varint,1,opt,name=TermX,proto3" json:"TermX,omitempty"`
	TermY int32 `protobuf:"varint,2,opt,name=TermY,proto3" json:"TermY,omitempty"`
}

func (x *ValuesCalculatorRequest) Reset() {
	*x = ValuesCalculatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Calculatrice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValuesCalculatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesCalculatorRequest) ProtoMessage() {}

func (x *ValuesCalculatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Calculatrice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesCalculatorRequest.ProtoReflect.Descriptor instead.
func (*ValuesCalculatorRequest) Descriptor() ([]byte, []int) {
	return file_Calculatrice_proto_rawDescGZIP(), []int{1}
}

func (x *ValuesCalculatorRequest) GetTermX() int32 {
	if x != nil {
		return x.TermX
	}
	return 0
}

func (x *ValuesCalculatorRequest) GetTermY() int32 {
	if x != nil {
		return x.TermY
	}
	return 0
}

type TableCalculatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiplicand int32 `protobuf:"varint,1,opt,name=Multiplicand,proto3" json:"Multiplicand,omitempty"`
	Multiplier   int32 `protobuf:"varint,2,opt,name=Multiplier,proto3" json:"Multiplier,omitempty"`
}

func (x *TableCalculatorRequest) Reset() {
	*x = TableCalculatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Calculatrice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableCalculatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCalculatorRequest) ProtoMessage() {}

func (x *TableCalculatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Calculatrice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCalculatorRequest.ProtoReflect.Descriptor instead.
func (*TableCalculatorRequest) Descriptor() ([]byte, []int) {
	return file_Calculatrice_proto_rawDescGZIP(), []int{2}
}

func (x *TableCalculatorRequest) GetMultiplicand() int32 {
	if x != nil {
		return x.Multiplicand
	}
	return 0
}

func (x *TableCalculatorRequest) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type TableCalculatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineOfTable []*OneLineInTableResponse `protobuf:"bytes,1,rep,name=LineOfTable,proto3" json:"LineOfTable,omitempty"`
}

func (x *TableCalculatorResponse) Reset() {
	*x = TableCalculatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Calculatrice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableCalculatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCalculatorResponse) ProtoMessage() {}

func (x *TableCalculatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Calculatrice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCalculatorResponse.ProtoReflect.Descriptor instead.
func (*TableCalculatorResponse) Descriptor() ([]byte, []int) {
	return file_Calculatrice_proto_rawDescGZIP(), []int{3}
}

func (x *TableCalculatorResponse) GetLineOfTable() []*OneLineInTableResponse {
	if x != nil {
		return x.LineOfTable
	}
	return nil
}

type OneLineInTableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiplicand int32 `protobuf:"varint,1,opt,name=Multiplicand,proto3" json:"Multiplicand,omitempty"`
	Multiplier   int32 `protobuf:"varint,2,opt,name=Multiplier,proto3" json:"Multiplier,omitempty"`
	Product      int32 `protobuf:"varint,3,opt,name=Product,proto3" json:"Product,omitempty"`
}

func (x *OneLineInTableResponse) Reset() {
	*x = OneLineInTableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Calculatrice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneLineInTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneLineInTableResponse) ProtoMessage() {}

func (x *OneLineInTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Calculatrice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneLineInTableResponse.ProtoReflect.Descriptor instead.
func (*OneLineInTableResponse) Descriptor() ([]byte, []int) {
	return file_Calculatrice_proto_rawDescGZIP(), []int{4}
}

func (x *OneLineInTableResponse) GetMultiplicand() int32 {
	if x != nil {
		return x.Multiplicand
	}
	return 0
}

func (x *OneLineInTableResponse) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *OneLineInTableResponse) GetProduct() int32 {
	if x != nil {
		return x.Product
	}
	return 0
}

var File_Calculatrice_proto protoreflect.FileDescriptor

var file_Calculatrice_proto_rawDesc = []byte{
	0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x32, 0x0a, 0x18, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x45, 0x0a, 0x17, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x65, 0x72, 0x6d, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x54, 0x65, 0x72, 0x6d, 0x58, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x65, 0x72, 0x6d, 0x59, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x65, 0x72, 0x6d, 0x59, 0x22, 0x5c, 0x0a, 0x16, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x5f, 0x0a, 0x17, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x65, 0x4f, 0x66, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4f, 0x6e, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x4c,
	0x69, 0x6e, 0x65, 0x4f, 0x66, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x76, 0x0a, 0x16, 0x4f, 0x6e,
	0x65, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x32, 0xa4, 0x02, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59,
	0x0a, 0x0e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x66, 0x72, 0x65,
	0x64, 0x65, 0x72, 0x69, 0x63, 0x73, 0x63, 0x68, 0x6d, 0x69, 0x64, 0x74, 0x2e, 0x66, 0x72, 0x2f,
	0x47, 0x6f, 0x44, 0x65, 0x6d, 0x6f, 0x30, 0x31, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x72, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Calculatrice_proto_rawDescOnce sync.Once
	file_Calculatrice_proto_rawDescData = file_Calculatrice_proto_rawDesc
)

func file_Calculatrice_proto_rawDescGZIP() []byte {
	file_Calculatrice_proto_rawDescOnce.Do(func() {
		file_Calculatrice_proto_rawDescData = protoimpl.X.CompressGZIP(file_Calculatrice_proto_rawDescData)
	})
	return file_Calculatrice_proto_rawDescData
}

var file_Calculatrice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Calculatrice_proto_goTypes = []interface{}{
	(*ResultCalculatorResponse)(nil), // 0: Calculator.ResultCalculatorResponse
	(*ValuesCalculatorRequest)(nil),  // 1: Calculator.ValuesCalculatorRequest
	(*TableCalculatorRequest)(nil),   // 2: Calculator.TableCalculatorRequest
	(*TableCalculatorResponse)(nil),  // 3: Calculator.TableCalculatorResponse
	(*OneLineInTableResponse)(nil),   // 4: Calculator.OneLineInTableResponse
}
var file_Calculatrice_proto_depIdxs = []int32{
	4, // 0: Calculator.TableCalculatorResponse.LineOfTable:type_name -> Calculator.OneLineInTableResponse
	1, // 1: Calculator.CalculatorService.AddOperation:input_type -> Calculator.ValuesCalculatorRequest
	1, // 2: Calculator.CalculatorService.SubOperation:input_type -> Calculator.ValuesCalculatorRequest
	2, // 3: Calculator.CalculatorService.TableOperation:input_type -> Calculator.TableCalculatorRequest
	0, // 4: Calculator.CalculatorService.AddOperation:output_type -> Calculator.ResultCalculatorResponse
	0, // 5: Calculator.CalculatorService.SubOperation:output_type -> Calculator.ResultCalculatorResponse
	3, // 6: Calculator.CalculatorService.TableOperation:output_type -> Calculator.TableCalculatorResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Calculatrice_proto_init() }
func file_Calculatrice_proto_init() {
	if File_Calculatrice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Calculatrice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultCalculatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Calculatrice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValuesCalculatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Calculatrice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableCalculatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Calculatrice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableCalculatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Calculatrice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneLineInTableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Calculatrice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Calculatrice_proto_goTypes,
		DependencyIndexes: file_Calculatrice_proto_depIdxs,
		MessageInfos:      file_Calculatrice_proto_msgTypes,
	}.Build()
	File_Calculatrice_proto = out.File
	file_Calculatrice_proto_rawDesc = nil
	file_Calculatrice_proto_goTypes = nil
	file_Calculatrice_proto_depIdxs = nil
}
